/**
 * MIT License
 *
 * Copyright (c) 2026–Present Xiao Hanyu (https://xiaohanyu.me)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 */

import { describe, expect, it } from "vitest";
import { hashBang, hasLicense, isGenerated } from "./detect.js";

describe("hasLicense", () => {
  it("detects copyright in file", () => {
    const buf = Buffer.from("// Copyright 2024 Test Corp\n");
    expect(hasLicense(buf)).toBe(true);
  });

  it("detects spdx identifier", () => {
    const buf = Buffer.from("// SPDX-License-Identifier: MIT\n");
    expect(hasLicense(buf)).toBe(true);
  });

  it("detects mozilla public license", () => {
    const buf = Buffer.from("// Mozilla Public License\n");
    expect(hasLicense(buf)).toBe(true);
  });

  it("is case-insensitive", () => {
    const buf = Buffer.from("// COPYRIGHT 2024\n");
    expect(hasLicense(buf)).toBe(true);
  });

  it("returns false when no license is present", () => {
    const buf = Buffer.from("const x = 1;\n");
    expect(hasLicense(buf)).toBe(false);
  });

  it("only checks first 1000 bytes", () => {
    const prefix = "\n".repeat(1001);
    const buf = Buffer.from(`${prefix}Copyright 2024\n`);
    expect(hasLicense(buf)).toBe(false);
  });

  it("handles empty buffer", () => {
    expect(hasLicense(Buffer.from(""))).toBe(false);
  });

  it("returns false for 'This is my license'", () => {
    const buf = Buffer.from("This is my license");
    expect(hasLicense(buf)).toBe(false);
  });

  it("returns false for 'copyright holder' doc comments", () => {
    const buf = Buffer.from("/** Copyright holder. */\n");
    expect(hasLicense(buf)).toBe(false);
  });

  it("returns false for CLI option strings", () => {
    const buf = Buffer.from('"-c, --copyright <holder>"');
    expect(hasLicense(buf)).toBe(false);
  });

  it("detects copyright with (c)", () => {
    const buf = Buffer.from("// Copyright (c) 2024 Test Corp\n");
    expect(hasLicense(buf)).toBe(true);
  });

  it("detects copyright with copyright symbol", () => {
    const buf = Buffer.from("// Copyright © 2024 Test Corp\n");
    expect(hasLicense(buf)).toBe(true);
  });
});

describe("isGenerated", () => {
  it("detects Go generated files", () => {
    const buf = Buffer.from("// Code generated by tool; DO NOT EDIT.\n");
    expect(isGenerated(buf)).toBe(true);
  });

  it("detects Go generated with one char prefix", () => {
    const buf = Buffer.from("x Code generated by tool; DO NOT EDIT.\n");
    expect(isGenerated(buf)).toBe(true);
  });

  it("detects Go generated with two char prefix", () => {
    const buf = Buffer.from("xx Code generated by tool; DO NOT EDIT.\n");
    expect(isGenerated(buf)).toBe(true);
  });

  it("detects cargo-raze generated files", () => {
    const buf = Buffer.from("DO NOT EDIT! Replaced on runs of cargo-raze\n");
    expect(isGenerated(buf)).toBe(true);
  });

  it("returns false for non-generated files", () => {
    const buf = Buffer.from("const x = 1;\n");
    expect(isGenerated(buf)).toBe(false);
  });

  it("handles empty buffer", () => {
    expect(isGenerated(Buffer.from(""))).toBe(false);
  });
});

describe("hashBang", () => {
  it("extracts shebang line", () => {
    const buf = Buffer.from("#!/usr/bin/env node\nconsole.log('hi');\n");
    expect(hashBang(buf)).toBe("#!/usr/bin/env node\n");
  });

  it("extracts xml declaration", () => {
    const buf = Buffer.from('<?xml version="1.0"?>\n<root/>\n');
    expect(hashBang(buf)).toBe('<?xml version="1.0"?>\n');
  });

  it("extracts doctype", () => {
    const buf = Buffer.from("<!doctype html>\n<html></html>\n");
    expect(hashBang(buf)).toBe("<!doctype html>\n");
  });

  it("extracts encoding declaration", () => {
    const buf = Buffer.from("# encoding: utf-8\nprint('hi')\n");
    expect(hashBang(buf)).toBe("# encoding: utf-8\n");
  });

  it("extracts frozen_string_literal", () => {
    const buf = Buffer.from("# frozen_string_literal: true\nputs 'hi'\n");
    expect(hashBang(buf)).toBe("# frozen_string_literal: true\n");
  });

  it("extracts php tag", () => {
    const buf = Buffer.from("<?php\necho 'hi';\n");
    expect(hashBang(buf)).toBe("<?php\n");
  });

  it("returns null for regular files", () => {
    const buf = Buffer.from("const x = 1;\n");
    expect(hashBang(buf)).toBeNull();
  });

  it("returns null for empty buffer", () => {
    expect(hashBang(Buffer.from(""))).toBeNull();
  });

  it("handles single line without newline", () => {
    const buf = Buffer.from("#!/bin/bash");
    expect(hashBang(buf)).toBe("#!/bin/bash");
  });

  it("is case-insensitive for prefixes", () => {
    const buf = Buffer.from('<?XML version="1.0"?>\n');
    expect(hashBang(buf)).toBe('<?XML version="1.0"?>\n');
  });

  it("extracts #\\ prefix", () => {
    const buf = Buffer.from("#\\\n");
    expect(hashBang(buf)).toBe("#\\\n");
  });

  it("extracts # escape prefix", () => {
    const buf = Buffer.from("# escape something\n");
    expect(hashBang(buf)).toBe("# escape something\n");
  });

  it("extracts # syntax prefix", () => {
    const buf = Buffer.from("# syntax=something\n");
    expect(hashBang(buf)).toBe("# syntax=something\n");
  });
});
