/**
 * MIT License
 *
 * Copyright (c) 2026–Present Xiao Hanyu (https://xiaohanyu.me)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 */

import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { SpdxMode } from "./license.js";
import { MissingLicenseError, run } from "./runner.js";

describe("run", () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "addlicense-"));
  });

  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  it("adds license to a file without one", async () => {
    const filePath = path.join(tmpDir, "test.js");
    await fs.writeFile(filePath, "console.log('hello');\n");

    const result = await run({
      holder: "Test Corp",
      license: "MIT",
      licenseFile: "",
      year: "2024",
      verbose: false,
      check: false,
      spdx: SpdxMode.Off,
      ignore: [],
      skip: [],
      patterns: [filePath],
    });

    expect(result.modified).toBe(1);
    const content = await fs.readFile(filePath, "utf-8");
    expect(content).toContain("Copyright (c) 2024 Test Corp");
    expect(content).toContain("console.log('hello');");
  });

  it("skips files that already have a license", async () => {
    const filePath = path.join(tmpDir, "test.js");
    await fs.writeFile(filePath, "// Copyright 2020 Someone\nconsole.log('hello');\n");

    const result = await run({
      holder: "Test Corp",
      license: "MIT",
      licenseFile: "",
      year: "2024",
      verbose: false,
      check: false,
      spdx: SpdxMode.Off,
      ignore: [],
      skip: [],
      patterns: [filePath],
    });

    expect(result.skipped).toBe(1);
    expect(result.modified).toBe(0);
  });

  it("skips generated files", async () => {
    const filePath = path.join(tmpDir, "test.go");
    await fs.writeFile(filePath, "// Code generated by tool; DO NOT EDIT.\npackage main\n");

    const result = await run({
      holder: "Test Corp",
      license: "Apache-2.0",
      licenseFile: "",
      year: "2024",
      verbose: false,
      check: false,
      spdx: SpdxMode.Off,
      ignore: [],
      skip: [],
      patterns: [filePath],
    });

    expect(result.skipped).toBe(1);
    expect(result.modified).toBe(0);
  });

  it("preserves hashbang line", async () => {
    const filePath = path.join(tmpDir, "test.sh");
    await fs.writeFile(filePath, "#!/bin/bash\necho hello\n");

    const result = await run({
      holder: "Test Corp",
      license: "MIT",
      licenseFile: "",
      year: "2024",
      verbose: false,
      check: false,
      spdx: SpdxMode.Off,
      ignore: [],
      skip: [],
      patterns: [filePath],
    });

    expect(result.modified).toBe(1);
    const content = await fs.readFile(filePath, "utf-8");
    expect(content.startsWith("#!/bin/bash\n")).toBe(true);
    expect(content).toContain("Copyright (c) 2024 Test Corp");
  });

  it("check mode detects missing licenses", async () => {
    const filePath = path.join(tmpDir, "test.js");
    await fs.writeFile(filePath, "console.log('hello');\n");

    let thrown: unknown;
    try {
      await run({
        holder: "Test Corp",
        license: "MIT",
        licenseFile: "",
        year: "2024",
        verbose: false,
        check: true,
        spdx: SpdxMode.Off,
        ignore: [],
        skip: [],
        patterns: [filePath],
      });
    } catch (err) {
      thrown = err;
    }

    expect(thrown).toBeInstanceOf(MissingLicenseError);
    expect((thrown as MissingLicenseError).missingFiles).toEqual([filePath]);
  });

  it("check mode passes when license exists", async () => {
    const filePath = path.join(tmpDir, "test.js");
    await fs.writeFile(filePath, "// Copyright 2020 Someone\nconsole.log('hello');\n");

    const result = await run({
      holder: "Test Corp",
      license: "MIT",
      licenseFile: "",
      year: "2024",
      verbose: false,
      check: true,
      spdx: SpdxMode.Off,
      ignore: [],
      skip: [],
      patterns: [filePath],
    });

    expect(result.missing).toBe(0);
  });

  it("check mode skips unsupported file types", async () => {
    const filePath = path.join(tmpDir, "test.xyz");
    await fs.writeFile(filePath, "content\n");

    const result = await run({
      holder: "Test Corp",
      license: "MIT",
      licenseFile: "",
      year: "2024",
      verbose: false,
      check: true,
      spdx: SpdxMode.Off,
      ignore: [],
      skip: [],
      patterns: [filePath],
    });

    expect(result.missing).toBe(0);
  });

  it("ignores files matching ignore patterns", async () => {
    const filePath = path.join(tmpDir, "test.js");
    await fs.writeFile(filePath, "console.log('hello');\n");

    const result = await run({
      holder: "Test Corp",
      license: "MIT",
      licenseFile: "",
      year: "2024",
      verbose: false,
      check: false,
      spdx: SpdxMode.Off,
      ignore: ["**/*.js"],
      skip: [],
      patterns: [filePath],
    });

    expect(result.modified).toBe(0);
    expect(result.skipped).toBe(0);
  });

  it("logs skipped files in verbose mode", async () => {
    const filePath = path.join(tmpDir, "test.js");
    await fs.writeFile(filePath, "console.log('hello');\n");

    const logSpy = vi.spyOn(console, "log").mockImplementation(() => {});

    await run({
      holder: "Test Corp",
      license: "MIT",
      licenseFile: "",
      year: "2024",
      verbose: true,
      check: false,
      spdx: SpdxMode.Off,
      ignore: ["**/*.js"],
      skip: [],
      patterns: [filePath],
    });

    expect(logSpy).toHaveBeenCalledWith(`skipping: ${filePath}`);
    logSpy.mockRestore();
  });

  it("skips files with skip extensions", async () => {
    const jsPath = path.join(tmpDir, "test.js");
    const tsPath = path.join(tmpDir, "test.ts");
    await fs.writeFile(jsPath, "console.log('hello');\n");
    await fs.writeFile(tsPath, "const x: number = 1;\n");

    const _result = await run({
      holder: "Test Corp",
      license: "MIT",
      licenseFile: "",
      year: "2024",
      verbose: false,
      check: false,
      spdx: SpdxMode.Off,
      ignore: [],
      skip: ["js"],
      patterns: [tmpDir],
    });

    const jsContent = await fs.readFile(jsPath, "utf-8");
    expect(jsContent).not.toContain("Copyright");
  });

  it("uses custom license file", async () => {
    const licenseFile = path.join(tmpDir, "custom.txt");
    const filePath = path.join(tmpDir, "test.js");
    await fs.writeFile(licenseFile, "Custom License by {{Holder}}");
    await fs.writeFile(filePath, "console.log('hello');\n");

    const result = await run({
      holder: "Test Corp",
      license: "",
      licenseFile: licenseFile,
      year: "2024",
      verbose: false,
      check: false,
      spdx: SpdxMode.Off,
      ignore: [],
      skip: [],
      patterns: [filePath],
    });

    expect(result.modified).toBe(1);
    const content = await fs.readFile(filePath, "utf-8");
    expect(content).toContain("Custom License by Test Corp");
  });

  it("handles SPDX-only mode", async () => {
    const filePath = path.join(tmpDir, "test.js");
    await fs.writeFile(filePath, "console.log('hello');\n");

    const result = await run({
      holder: "Test Corp",
      license: "MIT",
      licenseFile: "",
      year: "2024",
      verbose: false,
      check: false,
      spdx: SpdxMode.Only,
      ignore: [],
      skip: [],
      patterns: [filePath],
    });

    expect(result.modified).toBe(1);
    const content = await fs.readFile(filePath, "utf-8");
    expect(content).toContain("SPDX-License-Identifier: MIT");
    expect(content).not.toContain("Permission is hereby granted");
  });

  it("handles multiple patterns", async () => {
    const file1 = path.join(tmpDir, "a.js");
    const file2 = path.join(tmpDir, "b.ts");
    await fs.writeFile(file1, "// a\n");
    await fs.writeFile(file2, "// b\n");

    const result = await run({
      holder: "Test Corp",
      license: "MIT",
      licenseFile: "",
      year: "2024",
      verbose: false,
      check: false,
      spdx: SpdxMode.Off,
      ignore: [],
      skip: [],
      patterns: [file1, file2],
    });

    expect(result.modified).toBe(2);
  });

  it("skips unsupported file types", async () => {
    const filePath = path.join(tmpDir, "test.xyz");
    await fs.writeFile(filePath, "content\n");

    const result = await run({
      holder: "Test Corp",
      license: "MIT",
      licenseFile: "",
      year: "2024",
      verbose: false,
      check: false,
      spdx: SpdxMode.Off,
      ignore: [],
      skip: [],
      patterns: [filePath],
    });

    expect(result.modified).toBe(0);
    expect(result.skipped).toBe(1);
  });

  it("verbose mode prints output", async () => {
    const filePath = path.join(tmpDir, "test.js");
    await fs.writeFile(filePath, "console.log('hello');\n");

    const logSpy = vi.spyOn(console, "log").mockImplementation(() => {});

    const _result = await run({
      holder: "Test Corp",
      license: "MIT",
      licenseFile: "",
      year: "2024",
      verbose: true,
      check: false,
      spdx: SpdxMode.Off,
      ignore: [],
      skip: [],
      patterns: [filePath],
    });

    expect(logSpy).toHaveBeenCalledWith(`${filePath} modified`);
    logSpy.mockRestore();
  });

  it("handles undefined skip option", async () => {
    const filePath = path.join(tmpDir, "test.js");
    await fs.writeFile(filePath, "console.log('hello');\n");

    const result = await run({
      holder: "Test Corp",
      license: "MIT",
      licenseFile: "",
      year: "2024",
      verbose: false,
      check: false,
      spdx: SpdxMode.Off,
      ignore: [],
      skip: undefined as unknown as string[],
      patterns: [filePath],
    });

    expect(result.modified).toBe(1);
  });

  it("preserves hashbang without trailing newline", async () => {
    const filePath = path.join(tmpDir, "test.sh");
    await fs.writeFile(filePath, "#!/bin/bash", { encoding: "utf-8" });

    const result = await run({
      holder: "Test Corp",
      license: "MIT",
      licenseFile: "",
      year: "2024",
      verbose: false,
      check: false,
      spdx: SpdxMode.Off,
      ignore: [],
      skip: [],
      patterns: [filePath],
    });

    expect(result.modified).toBe(1);
    const content = await fs.readFile(filePath, "utf-8");
    expect(content.startsWith("#!/bin/bash\n")).toBe(true);
    expect(content).toContain("Copyright (c) 2024 Test Corp");
  });
});
